# Services to use in the local development machine

services:
  postgresql:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: localdb

  # latest neo4j
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
    volumes:
      - ./.data/neo4j:/data

  neo4j_data_loader:
    image: neo4j/neo4j-admin
    command: neo4j-admin database load neo4j --from-path=/backups
    volumes:
      - ./.data/neo4j:/data
      - ./projs/bjj:/backups
