[[session]]
name = "nvim config"
path = "~/.config/nvim"

[[session]]
name = "wezterm config"
path = "~/.config/wezterm"

[[session]]
name = "kitty config"
path = "~/.config/kitty"

[[session]]
name = "home"
path = "~"

[[session]]
name = "Beyond PY"
path = "~/loggi/py/apps/beyond"

[[session]]
name = "Beyond UI"
path = "~/loggi/ui/targets/beyond"

[[session]]
name = "Loggi Requests"
path = "~/loggi/loggi-requests"

[[session]]
name = "Loggi xproto"
path = "~/loggi/xproto"

[[session]]
name = "Loggi Wallet"
path = "~/loggi/wallet-api"

[[session]]
name = "Loggi Payment"
path = "~/loggi/beyond-payment"

[[session]]
name = "Loggi Web"
path = "~/loggi/web"
