[[session]]
name = "nvim config"
path = "~/.config/nvim"

[[session]]
name = "wezterm config"
path = "~/.config/wezterm"

[[session]]
name = "kitty config"
path = "~/.config/kitty"

[[session]]
name = "ghostty config"
path = "~/.config/ghostty"

[[session]]
name = "home"
path = "~"

[[session]]
name = "notes"
path = "~/Documents/Obsidian/vault/"

[[session]]
name = "Loggi Beyond PY"
path = "~/loggi/py/apps/beyond"

[[session]]
name = "Loggi Beyond UI"
path = "~/loggi/ui/targets/beyond"

[[session]]
name = "Loggi App"
path = "~/loggi/front-clientes-app-web"

[[session]]
name = "Loggi Requests"
path = "~/loggi/loggi-requests"

[[session]]
name = "Loggi xproto"
path = "~/loggi/xproto"

[[session]]
name = "Loggi wallet-api"
path = "~/loggi/wallet-api"

[[session]]
name = "Loggi beyond-payments"
path = "~/loggi/beyond-payment"

[[session]]
name = "Loggi Web"
path = "~/loggi/web"

[[session]]
name = "Loggi SPT"
path = "/opt/loggi/sales-pricing-tool"
