# Arctic (VSCode Dark+)
[colors]
foreground = "#d4d4d4"
background = "#1e1e1e"
cursor_bg = "#bbbbbb"
cursor_border = "#bbbbbb"
cursor_fg = "#ffffff"
selection_bg = "#3c3c3c"
selection_fg = "#ffffff"
split = "#444444"

ansi = [
  "#1e1e1e",
  "#f44747",
  "#6a9955",
  "#d0bc00",
  "#2fafff",
  "#c586c0",
  "#4dc9b0",
  "#dddddd"
]
brights = [
  "#808080",
  "#f55757",
  "#80ad6b",
  "#e1cb9e",
  "#6fabdc",
  "#d6a9d2",
  "#70d3bf",
  "#ffffff"
]

[colors.tab_bar]
background = "#1e1e1e"
foreground = "#D4D4D4"
inactive_tab_edge = "#1e1e1e"
inactive_tab_edge_hover = "#1e1e1e"

[colors.tab_bar.active_tab]
bg_color = "#04395e"
fg_color = "#ffffff"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#252526"
fg_color = "#D4D4D4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#2d2d2d"
fg_color = "#D4D4D4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#252526"
fg_color = "#D4D4D4"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#2d2d2d"
fg_color = "#ffffff"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"
