[colors]
foreground = "#ebdbb2"
background = "#282828"
cursor_bg = "#bdae93"
cursor_fg = "#665c54"
cursor_border = "#bdae93"
selection_fg = "#ebdbb2"
selection_bg = "#d65d0e"
scrollbar_thumb = "#3c3836"
split = "#3c3836"
ansi = [
  "#3c3836",
  "#cc241d",
  "#98971a",
  "#d79921",
  "#458588",
  "#b16286",
  "#689d6a",
  "#a89984",
]
brights = [
  "#928374",
  "#fb4934",
  "#b8bb26",
  "#fabd2f",
  "#83a598",
  "#d3869b",
  "#8ec07c",
  "#fbf1c7",
]
