# Monokai Pro (Classic)
[colors]
foreground = "#fdfff1"
background = "#272822"
cursor_bg = "#fdfff1"
cursor_border = "#fdfff1"
cursor_fg = "#272822"
selection_bg = "#6e7066"
selection_fg = "#fdfff1"
split = "#919288"

ansi = [
  "#1d1e19",
  "#f92672",
  "#a6e22e",
  "#e6db74",
  "#66d9ef",
  "#ae81ff",
  "#fd971f",
  "#fdfff1"
]
brights = [
  "#3b3c35",
  "#f92672",
  "#a6e22e",
  "#e6db74",
  "#66d9ef",
  "#ae81ff",
  "#fd971f",
  "#fdfff1"
]

[colors.tab_bar]
background = "#3b3c35"
foreground = "#fdfff1"
inactive_tab_edge = "#3b3c35"
inactive_tab_edge_hover = "#3b3c35"

[colors.tab_bar.active_tab]
bg_color = "#57584f"
fg_color = "#e6db74"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#3b3c35"
fg_color = "#c0c1b5"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#3b3c35"
fg_color = "#c0c1b5"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#3b3c35"
fg_color = "#c0c1b5"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#3b3c35"
fg_color = "#c0c1b5"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"
