# Monokai Pro
[colors]
foreground = "#fcfcfa"
background = "#2d2a2e"
cursor_bg = "#bbbbbb"
cursor_border = "#bbbbbb"
cursor_fg = "#fcfcfa"
selection_bg = "#5b595c"
selection_fg = "#fcfcfa"
split = "#939293"

ansi = [
  "#2d2a2e",
  "#ff6188",
  "#a9dc76",
  "#ffd866",
  "#78dce8",
  "#ab9df2",
  "#4dc9b0",
  "#fcfcfa"
]
brights = [
  "#403e41",
  "#ff6188",
  "#a9dc76",
  "#ffd866",
  "#78dce8",
  "#ab9df2",
  "#4dc9b0",
  "#fcfcfa"
]

[colors.tab_bar]
background = "#2d2a2e"
foreground = "#fcfcfa"
inactive_tab_edge = "#2d2a2e"
inactive_tab_edge_hover = "#2d2a2e"

[colors.tab_bar.active_tab]
bg_color = "#403e41"
fg_color = "#ffd866"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#403e41"
fg_color = "#c1c0c0"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#403e41"
fg_color = "#fcfcfa"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#403e41"
fg_color = "#c1c0c0"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#403e41"
fg_color = "#fcfcfa"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"
