[metadata]
name = 'NanoLight'

[colors]
foreground = "#37474F"
background = "#FFFFFF"
cursor_bg = "#37474F"
cursor_border = "#37474F"
cursor_fg = "#FFFFFF"
selection_bg = "#ECEFF1"
selection_fg = "#37474F"
scrollbar_thumb = "#37474F"
split = "#90A4AE"
ansi = ["#000000", "#42A5F5", "#66BB6A", "#26C6DA", "#AB47BC", "#E2C12F","#EF5350", "#FFFFFF"]
brights = ["#000000", "#42A5F5", "#66BB6A", "#26C6DA", "#AB47BC", "#E2C12F","#EF5350", "#FFFFFF"]

[colors.tab_bar]
background = "#ECEFF1"
inactive_tab_edge = "#37474F"
inactive_tab_edge_hover = "#263238"

[colors.tab_bar.active_tab]
bg_color = "#37474F"
fg_color = "#FFFFFF"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#ECEFF1"
fg_color = "#37474F"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#ECEFF1"
fg_color = "#37474F"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#ECEFF1"
fg_color = "#37474F"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#ECEFF1"
fg_color = "#37474F"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

