[colors]
foreground    = "#C6D5CF"
background    = "#0F191F"
cursor_fg     = "#0F191F"
cursor_bg     = "#CEDDD7"
cursor_border = "#0F191F"
selection_fg  = "#C6D5CF"
selection_bg  = "#3A3E3D"
ansi = ["#0F191F", "#DE6E7C", "#90FF6B", "#B77E64", "#8190D4", "#B279A7", "#66A5AD", "#C6D5CF"]
brights = ["#263945", "#E8838F", "#A0FF85", "#D68C67", "#92A0E2", "#CF86C1", "#65B8C1", "#98A39E"]
