[colors]
foreground    = "#202E18"
background    = "#E5EDE6"
cursor_fg     = "#E5EDE6"
cursor_bg     = "#202E18"
cursor_border = "#E5EDE6"
selection_fg  = "#202E18"
selection_bg  = "#ADE48C"
ansi = ["#E5EDE6", "#A8334C", "#567A30", "#944927", "#286486", "#88507D", "#3B8992", "#202E18"]
brights = ["#B3C6B6", "#94253E", "#3F5A22", "#803D1C", "#1D5573", "#7B3B70", "#2B747C", "#415934"]
