[colors]
background = "#002b36"
foreground = "#839496"

cursor_bg = "#708183"

selection_bg = "#073642"
selection_fg = "#93a1a1"

[colors.tab_bar]
background = "#073642"

[colors.tab_bar.active_tab]
fg_color = "#181926"
bg_color = "#268bd2"

[colors.tab_bar.inactive_tab]
fg_color = "#CAD3F5"
bg_color = "#586e75"

ansi = [ "#002b36", "#dc322f", "#859900", "#b58900", "#268bd2", "#d33682", "#2aa198", "#eee8d5" ]
brights = [ "#073642", "#cb4b16", "#586e75", "#657b83", "#839496", "#6c71c4", "#93a1a1", "#fdf6e3" ]

[metadata]
name = 'NeoSolarizedDark'
