[metadata]
name = 'NightOwl'

[colors]
foreground = "#D7DBE0"
background = "#001122"
cursor_bg = "#FAF39F"
cursor_border = "#FAF39F"
cursor_fg = "#011627"
selection_bg = "#637777"
selection_fg = "#D7DBE0"
scrollbar_thumb = "#475260"
split = "#102a44"
ansi = ["#000C1D", "#F78C6C", "#C5E478", "#7FDBCA", "#C792EA", "#ECC48D","#FF5874", "#CAECE6"]
brights = ["#001122", "#F78C6C", "#C5E478", "#7FDBCA", "#C792EA", "#ECC48D","#FF5874", "#CAECE6"]

[colors.tab_bar]
background = "#001122"
inactive_tab_edge = "#001122"
inactive_tab_edge_hover = "#000C1D"

[colors.tab_bar.active_tab]
bg_color = "#15283F"
fg_color = "#CAE3FD"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#001122"
fg_color = "#637777"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#001122"
fg_color = "#637777"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#001122"
fg_color = "#637777"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#001122"
fg_color = "#637777"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

