[metadata]
aliases = []
author = "kuntau"
name = "Nordic"

[colors]
foreground    = "#D8DEE9"
background    = "#242933"
cursor_bg     = "#D8DEE9"
cursor_border = "#D8DEE9"
cursor_fg     = "#242933"
selection_fg  = "#D8DEE9"
selection_bg  = "#2E3440"
split         = "#3B4252"
ansi          = [ "#191D24", "#BF616A", "#A3BE8C", "#EBCB8B", "#81A1C1",  "#B48EAD", "#8FBCBB", "#D8DEE9", ]
brights       = [ "#3B4252", "#D06F79", "#B1D196", "#F0D399", "#88C0D0",  "#C895BF", "#93CCDC", "#E5E9F0", ]


[colors.tab_bar]
background              = "#191D24"
inactive_tab_edge       = "#191D24"
inactive_tab_edge_hover = "#3B4252"

[colors.tab_bar.active_tab]
bg_color = "#2E3440"
fg_color = "#8FBCBB"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#191D24"
fg_color = "#D8DEE9"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#191D24"
fg_color = "#D8DEE9"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#191D24"
fg_color = "#D8DEE9"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#191D24"
fg_color = "#D8DEE9"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"
