[colors]
foreground = "#111111"
background = "#ffffff"
cursor_bg = "#00c2ff"
cursor_fg = "#111111"
cursor_border = "#00c2ff"
selection_fg = "#111111"
selection_bg = "#a89c14"
scrollbar_thumb = "#212121"
split = "#212121"
ansi = [
  "#212121",
  "#c30771",
  "#10a778",
  "#a89c14",
  "#008ec4",
  "#523c79",
  "#20a5ba",
  "#e0e0e0"
]
brights = [
  "#212121",
  "#fb007a",
  "#5fd7af",
  "#f3e430",
  "#20bbfc",
  "#6855de",
  "#4fb8cc",
  "#f1f1f1"
]
