import = ["/home/gustavo/.config/alacritty/themes/kanagawa.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "OperatorMono Nerd Font"
style = "Medium"

[font.bold_italic]
family = "OperatorMono Nerd Font"
style = "Medium Italic"

[font.italic]
family = "OperatorMono Nerd Font"
style = "Book Italic"

[font.normal]
family = "OperatorMono Nerd Font"
style = "Book"

[font.offset]
x = 0
y = 0

[window.padding]
x = 0
y = 0
