import = ["/home/gustavo/.config/alacritty/themes/kanagawa.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "MonoLisa"
style = "Bold"

[font.bold_italic]
family = "MonoLisa"
style = "Bold Italic"

[font.italic]
family = "MonoLisa"
style = "Regular Italic"

[font.normal]
family = "MonoLisa"
style = "Regular"

[font.offset]
x = 0
y = 1

[window.padding]
x = 0
y = 0
