import = ["/home/gustavo/.config/alacritty/themes/solarized_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "MonoLisa Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MonoLisa Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MonoLisa Nerd Font"
style = "Regular Italic"

[font.normal]
family = "MonoLisa Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = false
dynamic_title = true
opacity = 1

[window.padding]
x = 0
y = 0
