import = ["~/.config/alacritty/themes/nord.toml"]
live_config_reload = false

[env]
TERM = "xterm-256color"


[font]
size = 11

[font.bold]
family = "MonoLisa Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MonoLisa Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MonoLisa Nerd Font"
style = "Medium Italic"

[font.normal]
family = "MonoLisa Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 0

[window.padding]
x = 0
y = 0
