theme = "catppuccin_mocha"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[keys.normal]
C-s = ":w"

[keys.insert]
"C-s" = ["normal_mode", ":w"]
